name = "rss-plus-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# D1 数据库
[[d1_databases]]
binding = "DB"
database_name = "rss-reader-db"
database_id = "0b186b3e-bc0f-4879-b4d5-62b6cc259c4c"

# R2 存储桶
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "rss-plus-assets"

# KV 命名空间
[[kv_namespaces]]
binding = "KV"
id = "9e777b57dadf4f009bf795fb52255f5f"

# 环境变量
[vars]
R2_PUBLIC_URL = "https://pub-9b6cd3345b054bf587db6d138694cd63.r2.dev"
FRONTEND_URL = "https://rss-plus.pages.dev"

# 密钥 (通过 wrangler secret put JWT_SECRET 设置)

# 定时任务
[triggers]
crons = ["*/15 * * * *", "0 3 * * *"]

# 开发环境配置
[env.development]
[env.development.vars]
R2_PUBLIC_URL = "http://localhost:8787/r2"
FRONTEND_URL = "http://localhost:5173"
