name = "webrss"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "placeholder"
database_id = "placeholder"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "placeholder"

[[kv_namespaces]]
binding = "KV"
id = "placeholder"

[vars]
R2_PUBLIC_URL = "placeholder"
FRONTEND_URL = "placeholder"

[triggers]
crons = ["*/15 * * * *", "0 3 * * *"]
